language: node_js
sudo: false
node_js:
  - "4.8.4"
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - psql -d 'travis_ci_test' -U postgres -q -f 'test/setup.sql'
script:
  - npm test
  - npm run report-coverage
